"""cornerstone —— 从零自博弈的 Blokus Duo 模型。

C++ 引擎在 ``cornerstone._engine``（由 ``scripts/build.sh`` 编译产出）。
"""

from ._engine import (  # noqa: F401
    BOARD_N,
    MAX_PLIES,
    NUM_ACTIONS,
    NUM_CELLS,
    NUM_ORI,
    NUM_PIECES,
    NUM_PLANES,
    NUM_SCALARS,
    NUM_SYM,
    START_CELLS,
    TOTAL_SQUARES,
    Board,
    action_in_bounds,
    decode_action,
    encode_action,
    features_batch,
    legal_moves_reference,
    orientation_info,
    piece_names,
    piece_orientations,
    piece_sizes,
    random_playouts,
    rollout_value,
    sym_action_table,
    sym_cell_table,
)

__all__ = [
    "BOARD_N",
    "MAX_PLIES",
    "NUM_ACTIONS",
    "NUM_CELLS",
    "NUM_ORI",
    "NUM_PIECES",
    "NUM_PLANES",
    "NUM_SCALARS",
    "NUM_SYM",
    "START_CELLS",
    "TOTAL_SQUARES",
    "Board",
    "action_in_bounds",
    "decode_action",
    "encode_action",
    "features_batch",
    "legal_moves_reference",
    "orientation_info",
    "piece_names",
    "piece_orientations",
    "piece_sizes",
    "random_playouts",
    "rollout_value",
    "sym_action_table",
    "sym_cell_table",
]
